
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.110.230.117:3306/TEXT?useSSL=FALSE&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: root
    host: 47.110.230.117
    port: 6379
  jpa:
    hibernate:
     ddl-auto: update
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true

rsa:
  key:
   # pubKeyFile: C:\Users\JCH079\Desktop\Java\auth_key\id_key_rsa.pub
  #  priKeyFile: C:\Users\JCH079\Desktop\Java\auth_key\id_key_rsa
